### ISSUE TITLE
Stop duplicate forecasts

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalPredictions#137]
The no duplicate forecasts test fails because Travis builds twice? This wouldn't happen if we didn't use `append_csv()`. But is there a better way to drive Travis?

**Comment by ethanwhite** [comment]
This would be partly solved by #141, since the repo would no longer be changed as part of archiving the forecasts. This would stop the automatic double builds that currently happen. I think this should be sufficient in combination with the "one deployment per day rule" we currently have prevent any strictly identical forecasts.

**Comment by gmyenni** [comment]
I'm turning the 'no duplicate forecasts' test off for now.
https://github.com/weecology/portalPredictions/commit/e1b1efec18a026013c05a4bfd140d83cb8f2d16e

**Comment by ethanwhite** [comment]
It looks like solution to this is to use conditional builds and not build if the sender if our deploy bot:
https://docs.travis-ci.com/user/conditional-builds-stages-jobs#Specifying-conditions

However it us unclear how to identify the correct value for `sender`. I'll try a regex with `weecologydeploy` and see what happens.

**Comment by ethanwhite** [comment]
@henrykironde solved this in 8138d2b6b223b9aa5ffc81509f5f1ed4cb0106a7.
