### ISSUE TITLE
Edit archiving section

### ISSUE THREAD

**Issue by skmorgane** [weecology/portalPredictions#172]
If @ethanwhite makes the modifications he discussed in issue #141 then we will need to change the language in this section to reflect the new archiving process.

**Comment by ethanwhite** [comment]
With #178 we will keep the current archiving and add archiving to the forecasts repo. Since we want to focus on the central archiving in the paper we can rewrite with that in mind. If we want we can also mentioned that we are (separately) archiving the full code base and reuse the related language about why this is valuable.

**Comment by skmorgane** [comment]
We also need to check that the end of the presentation section is still correct. Currently we say that the website is archived with the forecast results.

**Comment by skmorgane** [comment]
We also need to check the 3rd paragraph of the discussion, which talks about how the current archiving system is sub-optimal. It may not be the case anymore.
