### ISSUE TITLE
Use weather forecasts

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#249]
@sdtaylor has already implemented this in his plant phenology work, so we just need to port it over.

**Comment by sdtaylor** [comment]
doing the stuff from the phenology work might be overkill for a single location. I'd recommend  using the source I talked about here https://github.com/weecology/portalPredictions/issues/158#issuecomment-359109352

**Comment by ethanwhite** [comment]
:+1: I'd totally forgotten about that earlier issue. Thanks for the PR!

**Comment by juniperlsimonis** [comment]
the forecast weather is awesome! thanks, @sdtaylor !
is it possible to get the predictions on the new moon dates, rather than by month? the models are now set up so that the time step is a lunar cycle for everything, including the forecasts. 
I looked at the code to your build_weather_forecast function and it looks like that might take some additional coding (i.e. not just flipping a switch from "month" to "newmoon"), but let me know if that functionality is already built in and I just missed it.
If it does require more coding, I'm happy to take care of that, unless you want to.

Also, if it does require some more coding, we will end up needing dates of future new moons, so I was wondering if that existed anywhere already, @gmyenni ? I poked around the portal data repo and I didn't find that anywhere. If we don't have it, I can create a simple data table that'll align newmoon dates with calendar dates for any time horizon we would conceivably be interested in...if I do that, though, where should that file live? (I would presume portalData, yeah?)

Edited to add

This actually applies to all of the weather data, not just the forecasts. Currently, the pevGARCH is using weather data that are summarized by calendar month, and then the month of the new moon date is used to access the weather data. This can add noise from the offset of calendar month and lunar month. it would make sense to tackle this all at once (get all of the covariates aligned with the lunar month, for both fitting and forecasting).

It seems like we could either switch to using the daily weather data (available via the weather() function in portalr) and then summarize it to lunar month within portal predictions, or we could add code and a toggle to the weather() function in portalr to summarize by lunar month. I would imagine the preference is to add the toggle to the portalr function, since other folks will likely want the data to align with the lunar months/newmoons.

As with the other stuff I mentioned, I'm totally game to jump in and code that unless someone else would like to.

**Comment by juniperlsimonis** [comment]
re: historical data alignment to newmoons, I've created a new "newmoon" level option in the weather() function that summarizes the weather data according to the newmoons, rather than the months, and have pushed it as part of a PR in that repo (https://github.com/weecology/portalr/pull/108).

**Comment by juniperlsimonis** [comment]
fyi: i am currently editing @sdtaylor 's get_climate_forecasts and build_weather_forecast functions in the model_tools script to work on the newmoon dates. 

the work is happening via PR #251 and i'm trying to keep my commits tidy, so i haven't pushed anything to that PR yet. 

just wanted to let folks know that i am working on it, even though nothings pushed yet.

**Comment by sdtaylor** [comment]
there is the  `get_future_moons` function in `model_tools.R` for downloading the dates of newmoons.

For the weather forecasts, I'm pretty sure there is a daily option within the server API that we can use.

**Comment by juniperlsimonis** [comment]
yeah, get_future_moons does exactly what I need, so no need to create a table of those dates or anything.

yup! i was able to get a daily option. it results in a call/table per metric, rather than one call/table with all of the metrics, but it works great

**Comment by juniperlsimonis** [comment]
I just pushed the updated code in #251, note however, that it requires an update to portalr that's in queue in https://github.com/weecology/portalr/pull/108
