### ISSUE TITLE
Versioning/Pushing new Docker images

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalPredictions#254]
I've been having to delete old containers before Docker will recognize and push new changes.

This describes a similar issue:
https://forums.docker.com/t/what-is-proper-way-to-rebuild-and-push-updated-image-to-docker-cloud/9516

**Comment by ethanwhite** [comment]
Hmmm. Well, I'm not sure why this is happening, but it makes me wonder if we shouldn't be tagging our docker containers separately anyway. That would make things more reproducible because we could go back and get the exact container we used at some point in the past to rerun a forecast. We could use either semantic version numbers starting at `1.0.0` (though I'm not sure what they'd mean in this context) and maybe just increment the minor version (middle) number when we update. Or we can tag them based on dates. Thoughts?

**Comment by gmyenni** [comment]
Wouldn't that also make it a bit easier for us to switch back to the previous image, if we push a new image but then things don't work out like we thought they would?

I think dates make sense.

**Comment by ethanwhite** [comment]
> Wouldn't that also make it a bit easier for us to switch back to the previous image, if we push a new image but then things don't work out like we thought they would?

Yep.

> I think dates make sense.

OK, let's do it.

**Comment by gmyenni** [comment]
So for portalPredictions to use it, I still need to add the latest tag for a new image, in addition to a named tag.
eg docker build -t weecology/portal_predictions:latest -t weecology/portal_predictions:2018-04-12 .

Or should we change this?

**Comment by ethanwhite** [comment]
Intersting. I think tagging both is fine.
