### ISSUE TITLE
add species level ESSS and autoARIMA models?

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/portalPredictions#255]
we're currently predicting species-level and total abundance in the nbGARCH and pevGARCH models, but the ESSS and autoARIMA models only predict total abundances.

for the sake of completeness and having some really naive species-level models for comparison, it seems like it would be nice to have species-level ESSS and autoARIMA models.

is there any reason why we don't do that now/shouldn't add that complexity?

**Comment by ethanwhite** [comment]
I think the only reason we didn't do it originally was because they modeled abundance as continuous, which we considered to be a reasonable approximation with total abundance numbers (>100), but thought might be more problematic with the small abundance values for many of the individual species. That said, since this is prediction focused I'm OK with fitting them to the species as well if you think that's reasonable.

**Comment by juniperlsimonis** [comment]
That makes sense. I can code them up pretty easily and see if they make at least some semi-reasonable predictions or if it's just a mess for the rare species.

**Comment by ethanwhite** [comment]
:+1:

**Comment by juniperlsimonis** [comment]
done with the code updates in portalcasting!
#295
