### ISSUE TITLE
decide on how to handle problematic historical forecasts

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/portalPredictions#261]
in instances where an existing model has been structurally altered to address a critical flaw, how do we want to handle historic forecasts made using the old ("incorrect") forecasts?

this has come up a few times that I'm aware of:
- the switch to newmoons and using the interpolated data set
- the shift to forecasting through recent missing values 
- the recalculation of the AutoArima AIC values (removal of the box-cox transformation)

**Comment by ethanwhite** [comment]
@skmorgane and I talked about this this morning and our current feeling is that this is a really confusing thing and we don't have a lot of clarity on it, but that our inclination is to keep them in their original state with both documentation of when the change was made and what it was and probably start a table that flags any "incorrect" forecasts so that we can exclude them if we want to focus on model comparisons.
