### ISSUE TITLE
adding website output to .gitignore

### ISSUE THREAD

**Issue by ha0ye** [weecology/portalPredictions#263]
Team Sandbox (@emchristensen and myself) are looking at new models and how someone outside Weecology might develop and test models.

It's unclear how much the infrastructure will change between now and a future release, but it would help if .gitignore included website files, as most users probably won't want to render locally and upload all the files through to GitHub. I don't think it will break anything with the website, since Travis CI is rendering the site remotely, right?

**Comment by ethanwhite** [comment]
No objections to the general change but it will be just a little tricky. We'll need to add a `-f` flag to the relevant git add command in `archive.sh` since adding these to .gitignore would stop them from being added and therefore the website wouldn't update. I'm not sure if the `-f` will cause the image files that get  deleted by the website build to be added or not. If not (and I think this is the case, but we should check) then we should be all set. If not we'll need modify the add command or tweak the way the website is built to avoid deleting the image files.

**Comment by ha0ye** [comment]
Alternatively, [this comment](https://github.com/rstudio/rmarkdown/issues/587#issuecomment-168437646) from @yihui provides a workaround to using output_dir that might prevent deletion of the image files.

**Comment by ethanwhite** [comment]
Sandboxing is now handled via `portalcasting` and website has been moved to https://github.com/weecology/portal-forecast-web
