### ISSUE TITLE
get observed data for function plot_sp_predicts 

### ISSUE THREAD

**Issue by skmorgane** [weecology/portalPredictions#28]
To add the actual observed numbers, we need code that takes the new moon being predicted and checks the database to see if that data has been entered and extracts that months results by 'level' and 'species'

**Comment by sdtaylor** [comment]
I think I do this using `abundance()` from PortalDataSummaries, with a little modification, here  https://github.com/weecology/portalPredictions/blob/master/viz_maincode.R#L24

**Comment by gmyenni** [comment]
I updated the abundance function so it doesn't rely on local repos. I also added an option to summarize by NewMoonNumber instead of period. I think the goal should be to use these functions (there is one for weather and there will be one for biomass as well) exclusively, rather than importing and modifying the data in multiple locations here. So let me know if there is anything else that you're doing that I could add to `abundance()` instead so you can use it.

**Comment by gmyenni** [comment]
I also added @sdtaylor 's functions to download and update data to `GetData.R` in PortalDataSummaries. So hopefully we can move all this data stuff out of this specific repo and into more general use over there.

**Comment by ethanwhite** [comment]
This is implemented now.
