### ISSUE TITLE
Language on use of weather data in forecasts

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#285]
> L245: You mention how you grab previous, observed weather data but don't
mention what you’re using as the weather forecast data to drive the forecasts.
In the repo portalPredictions/data you appear to provide models with both
weather data and NDVI to use as part of model calibration, but I don’t see the
inclusion of forecasts of these quantities, which makes me wonder if they’re
being used in the forecast at all

If @gmyenni or @juniperlsimonis has a few minutes to work up some basic language related to this that would be great.

**Comment by ethanwhite** [comment]
Here's a draft of some language that needs details in a couple of places:

> We do use these data in the forecasts. The pevGARCH model uses temperature,
precipitation, and NDVI as predictors. Forecasts for temperature and
precipitation are obtained from XXXX. Forecasts for NDVI are not currently
available and so we use a XXXX model to forecast future values. However, we have
avoided discussion of the specific models in this paper since exploration of the
infrastructure is already a sufficiently lengthy topic for discussion.

**Comment by juniperlsimonis** [comment]
We do use these data in the forecasts. The pevGARCH model uses temperature, precipitation, and NDVI as predictors. Forecasts for temperature and precipitation are obtained from the North American Multi Model Ensemble (NMME; Kirtman et al. 2014) downscaled to the Portal site. Forecasts for NDVI are not currently available and so we use a seasonal auto ARIMA model to forecast future values. However, we have avoided discussion of the specific models in this paper since exploration of the infrastructure is already a sufficiently lengthy topic for discussion.

----

From the NMME website: When using the NMME data, please cite the BAMS article describing the project (Kirtman et al. 2014) and in the acknowledgements please note that the NMME project and data dissemination is supported by NOAA, NSF, NASA and DOE. Please also acknowledge the help of NCEP, IRI and NCAR personnel in creating, updating and maintaining the NMME archive. 

The downscaling happens elsewhere (https://climate.northwestknowledge.net/RangelandForecast/download.php) but I'm not finding an explicit citation for that project.(@sdtaylor have you ever found a citation for the downscaling of the NMME?)

**Comment by ethanwhite** [comment]
Thanks @juniperlsimonis. This is perfect. I've added it to the letter and updated the PR.
