### ISSUE TITLE
Move HiperGator storage & runs to shared folder

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#344]
This will allow multiple folks to update and fix issues.

**Comment by henrykironde** [comment]
Remember to check permissions for shared folder for admins

**Comment by ethanwhite** [comment]
@henrykironde & I moved this over to `/orange/ewhite/PortalForecasts` and gave the group `rwx` permissions.

However, we can't seem to get the permissions to be maintained in the folder with the creation of new files. I think we had this issue with MATSS so @ha0ye may have some ideas.

**Comment by ha0ye** [comment]
I didn't dig too deeply into it, but I think it had to do with what permissions git sets when it does its stuff and generates new files in the `.git` folder. I believe there are 2 general solutions:
1. configure git settings (for the repo) so that it sets group `rwx` permissions when writing
2. configure the file system so that new files created in the directory have group `rwx` permissions by default

**Comment by henrykironde** [comment]
Thanks @ha0ye, we shall try that out.

**Comment by ethanwhite** [comment]
OK, @henrykironde and I solved this by following these instructions from HiPerGator:

https://help.rc.ufl.edu/doc/Sharing_Files

It requires all users editing any files in this directory to add `umask 0007` to their `.bashrc` file which will give `rw` permissions to everyone in the group to all of the files they create.
