### ISSUE TITLE
Move Dockerfile into portalcasting & update dockerhub on release

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#352]

**Comment by juniperlsimonis** [comment]
https://www.r-bloggers.com/running-your-r-script-in-docker/

**Comment by juniperlsimonis** [comment]
[i've got a PR open right now with the dockerfile moved over into portalcasting](https://github.com/weecology/portalcasting/pull/171)

and am following these instructions to set up automated builds on releases
https://docs.docker.com/docker-hub/builds/

**Comment by juniperlsimonis** [comment]
@ethanwhite i think i need more access privileges on the weecology dockerhub organization to do repo management needed for this.

**Comment by ethanwhite** [comment]
@juniperlsimonis - you are now an owner so you can do anything @gmyenni and I can do.

**Comment by juniperlsimonis** [comment]
thanks!

**Comment by juniperlsimonis** [comment]
I requested access for docker within the GH org now, that should have gotten sent to you @ethanwhite or @gmyenni 
looks like that's needed from the GH angle to make the connection work

**Comment by juniperlsimonis** [comment]
we are a go!
https://hub.docker.com/repository/docker/weecology/portalcasting
the portalcasting repo is now set up as its own entity on dockerhub so that
1. releases are automatically tagged with latest and the version number and pushed to dockerhub
2. pushes to master are tagged as dev and pushed to dockerhub
  - this allows testing of builds before fully releasing (nice!)
3. the docker build has its own subfolder (that's Rbuild ignored)   with its own README. that is used to create the front content of the dockerhub page 
  - i've minimized this compared to what's in the github repo

with portalcasting being set up via its own dockerfile now, we have a decision to make in terms of whether we would like to either
1. have portalcasting also update the portalpredictions docker image 
or
2. sunset the portalpredictions docker image and update the shell scripts in portalpredictions to grab the portalcasting image

my vote personally would be for #2, but i think both would be fine. 
I'm going to go ahead and close this issue, but think we should continue the discussion, @ethanwhite  and @henrykironde , and when we decide on how to integrate the new situation, we can create a new, specific issue
