### ISSUE TITLE
Automatically archive forecasts

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#47]
The core code for making forecasts should automatically archive the resulting forecasts. We *should* be able to do this using `rfigshare`.

**Comment by sdtaylor** [comment]
At first glance @skmorgane and Ifound that only new articles could be uploaded via `rfigshare`, currently published articles (we think) cannot be updated with new versions thru the `rfigshare`

**Comment by skmorgane** [comment]
Need to create a fake account to test if published filesets can have files added/updated. If not, we should contact carl boettinger or Scott chamberlain

**Comment by skmorgane** [comment]
Can we create filesets using rfigshare? Yes
Can we add files to a public fileset? Yes

Potential issues that need to be explored:

1. how to handle log-in credentials - especially for continuous integration to log in to figshare to archive forecasts

2. dealing with duplicate file issues. If the same file is loaded more than once, figshare will keep both version, with the exact same names. Once it is public, there is no changing this. But, when we add a file to a public fileset, the new file is **not** public. You have to use fs_make_public() again to get the new files added to the public set. This is a step where we can check to see if there are duplicate names and either delete the private duplicate or rename the private duplicate that explains why we reran the forecast. If Ethan has CI set up so that it does not run more than once a day, then we should be fine as no two forecast archives will have the same date. There may be scenarios where something went wrong with the forecast process and a bad archive/forecast was created and we reran everything to get a valid forecast and archive on the same say, but maybe that's a disaster scenario we don't want to engineer for right now?

3. Also, do we want separate all and control forecast filesets?

If the fileset already exists on figshare, then here's all the code we'll need (not including whatever we need to deal with authorization, which I think is being handled using a default in these function calls, but (I think) can be modified:
fs_upload(id, "./predictions/2016-11-4Allforecasts.csv")

fs_make_public(id)

**Comment by skmorgane** [comment]
A new figshare account has been set up under the name Portal Predictions (Predictions, Portal) and the old .csv archives have been uploaded. 

All that is now needed is to deal with the authentication issues to log into figshare each time we run a forecast.

**Comment by ethanwhite** [comment]
I worked on authentication yesterday and ran into some issues since rfigshare doesn't currently support the use of personal access tokens (see https://github.com/ropensci/rfigshare/issues/97). I'm going to open an issue asking for advice over there.

There is also a [Python figshare module](https://github.com/makkus/pigshare) that handles personal access tokens so that's another option.

**Comment by ethanwhite** [comment]
Another option is to consider using the Open Science Framework for this. They are good folks and one big advantage is that @ctb's group just released a [Python client](https://github.com/dib-lab/osf-cli) for interacting with it that seems really straight forward.

**Comment by ethanwhite** [comment]
OK, so OSF and the Python client work really nicely... *except* the resulting files aren't really archived in the way we want.

OSF has registrations, which are exactly what we need, but we don't appear to be able to trigger them automatically. 

I tried end running things by linking OSF to figshare, which looked super promising, but at least so far I can't figure out how to upload to the figshare storage through the OSF client (https://github.com/dib-lab/osf-cli/issues/96).

**Comment by ethanwhite** [comment]
And yet another option:
https://github.com/ropenscilabs/datastorr

**Comment by ethanwhite** [comment]
I appear to have the OSF client - figshare integration working in https://github.com/dib-lab/osf-cli/pull/100. Assuming this goes in then we can install the `master` version of `osfclient` and we should be good to go. The other advantage is that this route lets OSF deal with the complexities of the integration and so if, e.g., they add Zenodo in a few months and we'd rather archive to Zenodo, it's just a one line fix for us.

**Comment by ethanwhite** [comment]
Never mind. Once you make the figshare file set open adding new files don't actually get made public, so that would have to be done by hand. The tech just really isn't quite ready yet. Sigh. Will keep working on hacking our way around this.

**Comment by ethanwhite** [comment]
Opened an issue with OSF to see if they can implement what we need:
https://github.com/CenterForOpenScience/osf.io/issues/7494

**Comment by ethanwhite** [comment]
Wa ha ha ha. Closed finally.

**Comment by ctb** [comment]
What was the resolution?

**Comment by ethanwhite** [comment]
We are currently making a new release of the entire `portalPredictions` repository using the GitHub API after each new CI deployed forecast (see last few lines of [update_repo.sh](https://github.com/weecology/portalPredictions/blob/master/update_repo.sh). This then triggers the Zenodo-GitHub integration which archives the entire repo to Zenodo here:

https://doi.org/10.5281/zenodo.833438

Getting to the data is messier than what we've been doing, but the code is archived as well, so I'm not sure whether to think of this as imperfect, but functional, or better than what I'd been envisioning in the first place. Either way, it's actually working, which is all I can ask for for now.

I am still hoping that COS will add the change to their figshare integration that I need (or add something similar for Zendo, or add registration to their API) so that we can go back in that direction since it was my favorite of the options that didn't work.

**Comment by ctb** [comment]
sounds good!
